### PR TITLE
Controllers films users

### PR DESCRIPTION
**Pull request by kristina-sorokina**
Added controllers films users

### CODE REVIEW

**Comment by kristina-sorokina** [comment]
Please review

**Comment by kristina-sorokina** [comment]
Please, review - added @annotations to Film and User models to improve validation at the level of the models. 
Also changed 0< to 0<= to validate out the zero film duration.

**Comment by kristina-sorokina** [comment]
Please review - removed Builder Lombok annotation

**Review by SnikerZi — APPROVED** [review]
Молодец, неплохая работа, спасибо за правки.

**Pull request merged**
